### PR TITLE
DO NOT MERGE: CI PR TEST

### PR DESCRIPTION
**Pull request by uartie**
Testing intel ci pull-request

### CODE REVIEW

**Comment by uartie** [comment]
The intel CI will poll for new/changed PR's in this repository every 15 minutes and compile them.  Unfortunately, we can't give public access to the URL for build log details.  Only the CI result will be reported back to github (PASS/FAIL) for the compilation.  Hopefully that's better than nothing for now.  Thus, I will try to convey any failure details back to you if any arise.

**Comment by uartie** [comment]
Also, it's worth noting that any PR's here will be compiled against latest gstreamer and libva master dependencies (i.e. gstreamer,gst-plugins-base,gst-plugins-bad,libva)... if any of those are failing to compile, then PR will fail too

**Comment by ceyusa** [comment]
Thanks a lot!

It will be great if I feel that something could go wrong with old compiler/distros, just do the PR and if something fails, I could bother you ;)

**Comment by uartie** [comment]
On another note, intel ci still uses autotools tool chain (not mason)

**Pull request closed without merging**
